version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      time: "04:00"
      timezone: Europe/Vienna
      interval: weekly
    groups:
      deps:
        patterns:
          - '*'

  - package-ecosystem: composer
    directory: /
    schedule:
      time: "04:00"
      timezone: Europe/Vienna
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch

  - package-ecosystem: npm
    directory: /
    schedule:
      time: "04:00"
      timezone: Europe/Vienna
      interval: weekly
    groups:
      deps:
        patterns:
          - '*'